### PR TITLE
Fixed pkg-config generation

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
Ported https://github.com/oneapi-src/level-zero/pull/243

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@conda-forge-admin, please rerender

**Comment by ilya-lavrenov** [comment]
@conda-forge-admin, please rerender

**Comment by ilya-lavrenov** [comment]
@hmaarrfk please, have a look.

**Review by hmaarrfk — COMMENTED** [review]
Thank you Ilya!

I'll let the maintainers have some time here.

Some context: @conda-forge/level-zero these changes should help ilya better depend on this package in downstream projects.

**Comment by oleksandr-pavlyk** [comment]
@ilya-lavrenov Did you also open a PR upstream with your changes to the CMake script?

**Review by kurapov-peter — APPROVED** [review]
Looks good to me. I assume @ilya-lavrenov will support the patches going forward (I see you're adding yourself to the maintainers list). Some context for the patch would still be nice, so that others could fix problems in the future if any.

**Comment by ilya-lavrenov** [comment]
> Looks good to me. I assume @ilya-lavrenov will support the patches going forward (I see you're adding yourself to the maintainers list). Some context for the patch would still be nice, so that others could fix problems in the future if any.

As mentioned in the PR description, this patch is waiting for upstream merge https://github.com/oneapi-src/level-zero/pull/243
If you could review it as well, it would be great.

**Comment by hmaarrfk** [comment]
I can also take a look this weekend and maybe even test it

**Comment by ilya-lavrenov** [comment]
BTW, the patch to upstream has been merged.

**Comment by hmaarrfk** [comment]
Old:

```
$ pkg-config --libs --debug level-zero
-L/home/conda/feedstock_root/build_artifacts/intel-level-zero_1732543272614/work/install/lib64 -lze_loader
```

Current:

```
$ pkg-config --libs --debug level-zero
-L/home/mark/miniforge3/envs/dev/lib/pkgconfig/../ -lze_loader
```

seem good! 

Thank you @ilya-lavrenov for working through these many integration challenges!

I know its really difficult to reconcile the fact that many upstream projects simply vendor code, and that at conda-forge we push strongly toward shared libraries!

**Pull request merged**
